include: package:very_good_analysis/analysis_options.yaml


analyzer:  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.config.dart"

  errors:
    public_member_api_docs: ignore
    invalid_annotation_target: ignore

  plugins:
      - dart_code_metrics

dart_code_metrics:
  metrics-exclude:
    - test/**
  rules:
    # Dart
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-conditional-expressions
    - prefer-trailing-comma

    # Flutter
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate