name: tennis_app
description: "Test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  datetime_picker_formfield_new: ^2.1.0
  dio: ^5.5.0+1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0 
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/courts.json
    - assets/json/trainers.json
